alter table "public"."designation" drop constraint "designation_pkey";

alter table "public"."employee" drop constraint "employee_pkey";

drop index if exists "public"."designation_pkey";

drop index if exists "public"."employee_pkey";

drop table "public"."designation";

drop table "public"."employee";

create table "public"."test1" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."test1" enable row level security;

create table "public"."test2" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."test2" enable row level security;

CREATE UNIQUE INDEX "Test 1_pkey" ON public.test1 USING btree (id);

CREATE UNIQUE INDEX "Test2_pkey" ON public.test2 USING btree (id);

alter table "public"."test1" add constraint "Test 1_pkey" PRIMARY KEY using index "Test 1_pkey";

alter table "public"."test2" add constraint "Test2_pkey" PRIMARY KEY using index "Test2_pkey";

grant delete on table "public"."test1" to "anon";

grant insert on table "public"."test1" to "anon";

grant references on table "public"."test1" to "anon";

grant select on table "public"."test1" to "anon";

grant trigger on table "public"."test1" to "anon";

grant truncate on table "public"."test1" to "anon";

grant update on table "public"."test1" to "anon";

grant delete on table "public"."test1" to "authenticated";

grant insert on table "public"."test1" to "authenticated";

grant references on table "public"."test1" to "authenticated";

grant select on table "public"."test1" to "authenticated";

grant trigger on table "public"."test1" to "authenticated";

grant truncate on table "public"."test1" to "authenticated";

grant update on table "public"."test1" to "authenticated";

grant delete on table "public"."test1" to "service_role";

grant insert on table "public"."test1" to "service_role";

grant references on table "public"."test1" to "service_role";

grant select on table "public"."test1" to "service_role";

grant trigger on table "public"."test1" to "service_role";

grant truncate on table "public"."test1" to "service_role";

grant update on table "public"."test1" to "service_role";

grant delete on table "public"."test2" to "anon";

grant insert on table "public"."test2" to "anon";

grant references on table "public"."test2" to "anon";

grant select on table "public"."test2" to "anon";

grant trigger on table "public"."test2" to "anon";

grant truncate on table "public"."test2" to "anon";

grant update on table "public"."test2" to "anon";

grant delete on table "public"."test2" to "authenticated";

grant insert on table "public"."test2" to "authenticated";

grant references on table "public"."test2" to "authenticated";

grant select on table "public"."test2" to "authenticated";

grant trigger on table "public"."test2" to "authenticated";

grant truncate on table "public"."test2" to "authenticated";

grant update on table "public"."test2" to "authenticated";

grant delete on table "public"."test2" to "service_role";

grant insert on table "public"."test2" to "service_role";

grant references on table "public"."test2" to "service_role";

grant select on table "public"."test2" to "service_role";

grant trigger on table "public"."test2" to "service_role";

grant truncate on table "public"."test2" to "service_role";

grant update on table "public"."test2" to "service_role";


