create table "public"."designation" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."designation" enable row level security;

CREATE UNIQUE INDEX designation_pkey ON public.designation USING btree (id);

alter table "public"."designation" add constraint "designation_pkey" PRIMARY KEY using index "designation_pkey";

grant delete on table "public"."designation" to "anon";

grant insert on table "public"."designation" to "anon";

grant references on table "public"."designation" to "anon";

grant select on table "public"."designation" to "anon";

grant trigger on table "public"."designation" to "anon";

grant truncate on table "public"."designation" to "anon";

grant update on table "public"."designation" to "anon";

grant delete on table "public"."designation" to "authenticated";

grant insert on table "public"."designation" to "authenticated";

grant references on table "public"."designation" to "authenticated";

grant select on table "public"."designation" to "authenticated";

grant trigger on table "public"."designation" to "authenticated";

grant truncate on table "public"."designation" to "authenticated";

grant update on table "public"."designation" to "authenticated";

grant delete on table "public"."designation" to "service_role";

grant insert on table "public"."designation" to "service_role";

grant references on table "public"."designation" to "service_role";

grant select on table "public"."designation" to "service_role";

grant trigger on table "public"."designation" to "service_role";

grant truncate on table "public"."designation" to "service_role";

grant update on table "public"."designation" to "service_role";


